#!/bin/sh
#
# $1 = To: address
# $2 = In-Reply-To/References address
# $3..$N = list of patches

[ $# -lt 3 -o -z "$3" ] && \
	{ echo "usage: $0 <to> \"<in-reply-to>\" *.patch"; exit 0; }

to="$1"
in_reply_to="$2"
shift 2

for patch in "$@"
do
	git send-email \
		--to "$to" \
		--in-reply-to "$in_reply_to" \
		--no-thread --confirm auto \
		"$patch"

	sleep 1
done;

